version: '3.8'

services:
    app:
      platform: linux/arm64
      build:
        context: .
        dockerfile: Dockerfile
      image: todo_api
      environment:
        - RAILS_ENV=production
        #- PASSENGER_MIN_INSTANCES=2
      volumes:
        - ./storage:/app/storage
        - /var/www/todo_api/shared/local_env.yml:/app/local_env.yml
        - /var/www/todo_api/shared/log:/app/log
      ports:
        - "3000:3000"  # Passenger listens here

# Other services (DB, Redis, etc.)
#   db:
#       image: arm64v8/postgres:13
#           volumes:
#                 - pg_data:/var/lib/postgresql/data
#
#                 volumes:
#                   pg_data:
